version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Core Packages (Microsoft. / System.) shall be grouped together
      core-packages:
        patterns:
          - "Microsoft.*"
          - "System.*"
      # Serilog packages shall be grouped together
      serilog:
        patterns:
          - "Serilog"
          - "Serilog.*"
      # Testcontainers
      testcontainers:
        patterns:
          - "Testcontainers"
          - "Testcontainers.*"
      # MSTest
      mstest:
        patterns:
          - "MSTest.*"
      # xUnit
      xunit:
        patterns:
          - "xunit"
          - "xunit.*"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "mcr.microsoft.com/dotnet/*"
        update-types:
          - "version-update:semver-major"
