name: Mirror to Codeberg

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Mirror to Codeberg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: mirror-repository
        uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: 'ssh://git@codeberg.org/FloppyBot/FloppyBot.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: 'true'
